# Generated by Django 4.2.1 on 2023-06-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usr', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usr', models.CharField(max_length=30)),
                ('apellido_usr', models.CharField(max_length=30)),
                ('correo_usr', models.CharField(max_length=50)),
                ('telefono_usr', models.IntegerField(null=True)),
                ('rol_usr', models.IntegerField()),
                ('fec_creacion_usr', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
