# Generated by Django 4.2.1 on 2023-06-04 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id_pqrs', models.IntegerField(primary_key=True, serialize=False)),
                ('texto_pqrs', models.CharField(max_length=250)),
                ('correo_pqrs', models.CharField(max_length=50)),
                ('telefono_pqrs', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id_pblc', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_pblc', models.CharField(max_length=25)),
                ('correo_pblc', models.CharField(max_length=50)),
                ('telefono_pblc', models.IntegerField(null=True)),
                ('rol_pblc', models.IntegerField()),
                ('contrasena_pblc', models.CharField(max_length=12)),
                ('fec_creacion_pblc', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.usuarios')),
            ],
        ),
    ]
