# Generated by Django 4.2.1 on 2023-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_pqrs_table_alter_public_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='cuerpo_pblc',
            field=models.CharField(max_length=500),
        ),
    ]
