# Generated by Django 4.2.1 on 2023-06-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_public_cuerpo_pblc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.public')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.usuarios')),
            ],
        ),
    ]
