# Generated by Django 4.2.1 on 2023-06-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='publicacion',
            new_name='id_pblc',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='id_usr',
        ),
    ]
