# Generated by Django 4.2.1 on 2023-06-07 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_rename_publicacion_comentario_id_pblc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_pblc',
            new_name='publicacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='id_usr',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_creacion',
        ),
    ]
