# Generated by Django 4.2.1 on 2023-06-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id_calculo', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=100)),
                ('consumo_wh', models.FloatField()),
                ('promedio_horas_diarias', models.FloatField()),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.calculo')),
            ],
        ),
    ]
