# Generated by Django 4.2.1 on 2023-06-10 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_remove_dato_calculo_delete_calculo_delete_dato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='id_pblc',
        ),
        migrations.AddField(
            model_name='public',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
