# Generated by Django 4.2.1 on 2023-06-10 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_remove_public_id_pblc_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='id',
        ),
        migrations.AddField(
            model_name='public',
            name='id_pblc',
            field=models.IntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
