# Utiliza la imagen base de Python para Django
FROM python:3.11

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de tu proyecto al contenedor
COPY . /app

# Instala las dependencias de tu proyecto
RUN pip install -r requirements.txt

# Expone el puerto 8000 para acceder a tu aplicación Django
EXPOSE 8000

# Ejecuta el comando para iniciar tu aplicación Django
CMD python manage.py runserver 0.0.0.0:8000
